### ISSUE TITLE
NPM package comes without Control.Geocoder.js

### ISSUE THREAD

**Issue by AW-UC** [perliedman/leaflet-control-geocoder#89]
As far as I understand the scripts defined in https://github.com/perliedman/leaflet-control-geocoder/blob/master/package.json, the distributed NPM package should include a `dist` directory with the browserified output. This directory should then be added to `gh-pages`. However, if I install version 1.3.0 it comes without `dist` directory. ~~and it is not present on these pages either~~(**Edit**: My bad, chose wrong branch.)

**Comment by AW-UC** [comment]
A closer look reveals that the npm package is really messed up ;-)

**Comment by perliedman** [comment]
Could you elaborate on what "really messed up" means in this case?

**Comment by AW-UC** [comment]
Yeah, sure. I just meant that it does not include the browserified `Control.Geocoder.js` at its root folder. It is included in a `_site` folder though, which mostly contains redundant copies of the files in the root folder. This is the tree for `1.3.0`:
```
leaflet-control-geocoder
│   .jshintrc
│   .npmignore
│   bower.json
│   Control.Geocoder.css
│   LICENSE
│   package.json
│   README.md
│   
├───demo
│       index.html
│       
├───images
│       geocoder.png
│       throbber.gif     
│                       
├───scripts
│       build.sh
│       publish.sh
│       
├───src
│   │   control.js
│   │   index.js
│   │   util.js
│   │   
│   └───geocoders
│           bing.js
│           google.js
│           mapbox.js
│           mapquest.js
│           nominatim.js
│           photon.js
│           what3words.js
│           
├───test
│       position.html
│       touch.html
│       
└───_site
    │   bower.json
    │   Control.Geocoder.css
    │   LICENSE
    │   package.json
    │   README.md
    │   
    ├───demo
    │       index.html
    │       
    ├───dist
    │   │   Control.Geocoder.css
    │   │   Control.Geocoder.js
    │   │   
    │   └───images
    │           geocoder.png
    │           throbber.gif
    │           
    ├───images
    │       geocoder.png
    │       throbber.gif
    │       
    ├───scripts
    │       build.sh
    │       publish.sh
    │       
    ├───src
    │   │   control.js
    │   │   index.js
    │   │   util.js
    │   │   
    │   └───geocoders
    │           bing.js
    │           google.js
    │           mapbox.js
    │           mapquest.js
    │           nominatim.js
    │           photon.js
    │           what3words.js
    │           
    └───test
            position.html
            touch.html
```
Whereas this is `1.2.1`:
```
leaflet-control-geocoder
│   .jshintrc
│   bower.json
│   Control.Geocoder.css
│   Control.Geocoder.js
│   LICENSE
│   package.json
│   README.md
│   
├───demo
│       index.html
│       
├───images
│       geocoder.png
│       throbber.gif
│                       
└───test
        position.html
        touch.html
```
Can you reproduce it?

**Comment by AW-UC** [comment]
It also seems that https://github.com/perliedman/leaflet-control-geocoder/blob/gh-pages/Control.Geocoder.js and http://www.liedman.net/leaflet-control-geocoder/Control.Geocoder.js correspond to ece970129bb87f62117e64ae90e49ad4c06d6b7a but not to a9e162ff5a9010c2c9a7c7cbdc3face00af72203 (1.3.0). Furthermore, release 1.3.0 appears on NPM but not here on Github (compare https://www.npmjs.com/package/leaflet-control-geocoder and https://github.com/perliedman/leaflet-control-geocoder/releases).

**Comment by perliedman** [comment]
Ok, thanks for the details!

Some comments:

* `_site` should definitely not be part of the package, it's an accident from my packaging
* My plan was to _not_ include `dist` files in the npm package: the reasoning behind it is that you most likely use Browserify or similar if you use the npm package, and just requiring the module should do the trick; I realize this might not be how everyone does it, so maybe it makes sense to include `dist` in the package after all
* 1.3.0 not showing up on GitHub is probably me forgetting to push tags

Anyway, thanks again for checking out the details and notifying me. I'll add `dist` to the package in the next release, and try up some of the mess that got dragged into the 1.3.0 release.

Unfortunately, I'm a bit pressed for time the coming week or so, so it might be a while before I can fix this.

**Comment by perliedman** [comment]
I've released 1.3.1 which should contain the `dist` directory!

Thanks again for the heads up about the broken package.

**Comment by rpadovani** [comment]
The package installed with bower is still broken, and doesn't include Control.Geocoder.js

**Comment by perliedman** [comment]
@rpadovani sorry, I don't user bower, nor do I know how bower works. The `bower.json` in this project was contributed by someone else.

I guess the problem is that the repo no longer contains the distribution files, since you're supposed to build them from the source. Leaflet does the same thing, but I don't know how it works with bower.

Help in this area is very welcome!
